valhalla/sif

src/sif/autocost.cc
@dgearhart @dnesbitt61 @kevinkreiser
=> added country_crossing_factor and avoid_country_crossings

src/sif/autocost.cc
@dgearhart @dnesbitt61 @kevinkreiser
=> removed country crossing flag.

src/sif/autocost.cc
Finally.....country crossing works.
=> moved False intersection logic down.

Makefile.am, src/sif/dynamiccost.cc, src/sif/edgelabel.cc, src/sif/pedestriancost.cc, src/sif/transitcost.cc, valhalla/sif/costconstants.h, valhalla/sif/dynamiccost.h, valhalla/sif/edgelabel.h, valhalla/sif/transitcost.h
Added max_distance to pedestrian cost. Added walking distance to each EdgeLabel constructor. Add operator += to Cost. Added Use to the edge label so we can track the predecessor edge use/type.
=> Adding TransitCost. 

src/sif/edgelabel.cc, valhalla/sif/edgelabel.h
Also add walking distance to the existing Update method and remove mode
(not sure if we want to allow the mode to change.
=> Add a 2nd update method which includes and updated tripId and blockId.

src/sif/pedestriancost.cc
with more comments and clearer "disallowed" cases.
Do not check for U-turn when disembarking transit (fixes NYC transit cases)
=> Rework the Allowed method - fix NYC transit

src/sif/autocost.cc
Basically the transition costs are increased if node density is above average. This should help increase route times in urban areas. We can tune these factors (or disable them by setting all to 1.0) as needed.
=> Add a density factor for use in edge transition costing.

src/sif/edgelabel.cc, valhalla/sif/edgelabel.h
Indicates the path has transit somewhere up this point.
=> Add has_transit flag. 

src/sif/autocost.cc, src/sif/edgelabel.cc, valhalla/sif/edgelabel.h
Only needed for the multimodal case
=> Remove walking distance from regular EdgeLabel constructor and Update

README.md
Looks like I forgot to PR this one when I did the others...
=> Trivial typo fixes

src/sif/bicyclecost.cc
Next steps are to modulate speed based on surface types and to add penalties for undesirable roads
=> Use time as the cost basis rather than distance. 

src/sif/bicyclecost.cc
Modulate speed based on bicycle type and road surface. Use a single "useroads" factor indicating willingness to use roads (0-not too willing, 1 - dont mind). Add weightings based on road class. Add default average speed based on bicycle type.
=> Update so that costs are time based.

src/sif/bicyclecost.cc, src/sif/pedestriancost.cc
In bicyclecost the tag name is now "use_roads"
=> Change driveway factor default to 5 for pedestrian. 

src/sif/autocost.cc, src/sif/bicyclecost.cc
and rework to explicity separate time and penalty parts of the cost.
=> Remove false intersection cost special case 

src/sif/pedestriancost.cc
=> Update TransitionCostReverse call to match the new arguments 

src/sif/bicyclecost.cc, src/sif/pedestriancost.cc
Validate input walking speed is within a reasonable range.
=> Change to "cycling_speed' on input

src/sif/bicyclecost.cc
Reduce the gap in classification weights so if rider prefers roads it does not penalize so much. Do not penalize for higher speeds if a bike lane exists.
=> Slight Tweaks to Penalties

src/sif/bicyclecost.cc
Reduce density factors for transition costs. Favor walkways a little more. Increase penalty for speeds above threshold and for some road classifications. Also take into account the speed and class on roads where separated bike lane exists (may be less desirable for inexperienced cyclists to be on bike lanes on higher speed/class roads).
=> Tune bicycle costing.

src/sif/bicyclecost.cc
Add kGradeBasedSpeedFactor (modifies speed based on weighted grade) and grade_weight array (additional modifier to the cost). TODO - next step is to populate the grade_weight array based on the input hilliness factor (or whatever we call the "avoid hills" factor).
=> Add kGradeBasedSpeedFactor and grade_weight array

src/sif/bicyclecost.cc
so when use_roads is near 1 the difference in weights is minimal. 
Update the grade_penalties and test with some known cases in MD.
Now seems to be a better balance between useroads and usehills factors.
=> Redo the weights applied to road classifications

src/sif/autocost.cc, src/sif/bicyclecost.cc
Needed for many to one time+distance matrix computation
=> Add TransitionCostReverse to autocost

Makefile.am, src/sif/truckcost.cc, valhalla/sif/truckcost.h
Has some default vehicle characteristics. No support yet for special access restrictions - need to add those to the data and add methods to access them within costing.
=> Initial truck costing methods.

src/sif/autocost.cc, src/sif/edgelabel.cc, src/sif/truckcost.cc, valhalla/sif/edgelabel.h
Check for transition onto toll edge as part of transition cost (to allow toll penalty).
=> Add toll flag to EdgeLabel. 

src/sif/edgelabel.cc, valhalla/sif/edgelabel.h
to improve performance of bidirectional A*. Remove Attributes struct and use bit fields directly.
=> Add opposing edge (GraphId) and opposing edge index 

src/sif/autocost.cc, src/sif/bicyclecost.cc, src/sif/pedestriancost.cc, src/sif/transitcost.cc, src/sif/truckcost.cc, valhalla/sif/dynamiccost.h
Fixes Uturn cases on other than local hierarchies.
=> Add predecessor edge to AllowedReverse.

src/sif/bicyclecost.cc
=> slight updates so that cycleways are favored by default vs roads

src/sif/pedestriancost.cc
(e.g., between sides of a doubly digitized road).
=> Add slight maneuver change penalty to help prevent small zig-zags

src/sif/autocost.cc, src/sif/bicyclecost.cc, src/sif/pedestriancost.cc
(this messes up many_to_one time distance matrix method).
=> Remove check against not_thu within AllowedReverse 

src/sif/dynamiccost.cc, src/sif/transitcost.cc, src/sif/truckcost.cc, valhalla/sif/dynamiccost.h
Fixes routes in test file 1, 5, 6, 7, 8.  2 is better not the best.  3 and 4 has the leave a station and go back in issue.
=> Gk - updated transit costing

src/sif/dynamiccost.cc, src/sif/pedestriancost.cc, src/sif/transitcost.cc, valhalla/sif/dynamiccost.h
updated TransferCost to produce better routes. 
Default Transfer cost no longer is multiplied by the transfer_factor_. 
Updated default values. 
Some clean up as well. 
TransferCostFactor removed.
=> refactor for cleaner routes.

src/sif/pedestriancost.cc
max_distance_mm_ is now transit_start_end_max_distance_ and max_transfer_distance_mm_ is now transit_transfer_max_distance_.
=> transit walking updates

src/sif/dynamiccost.cc, src/sif/transitcost.cc, valhalla/sif/dynamiccost.h
This record is not stored in tiles anymore.
=> Remove TransitTransfer from TransferCost

src/sif/dynamiccost.cc, valhalla/sif/dynamiccost.h, valhalla/sif/hierarchylimits.h
=> Allow separate factor for the expansion within distance

src/sif/transitcost.cc
updated GetFilter to excluded ferries for the Transit Land stop conflation.
=> updated transit filter

src/sif/edgelabel.cc, src/sif/pedestriancost.cc, valhalla/sif/edgelabel.h
Change stop Id to a GraphId and have it use the opp_edgeid GraphId (which was only used for bidirectional A*).
=> Change walking_distance to path_distance. 

src/sif/pedestriancost.cc
=> added logic to avoid ferries via use_ferry flag.  Defaults to 1 (use ferries please)
