valhalla/sif

Makefile.am
src/sif/autocost.cc
src/sif/bicyclecost.cc
src/sif/dynamiccost.cc
src/sif/edgelabel.cc
src/sif/pedestriancost.cc
valhalla/sif/costconstants.h
valhalla/sif/dynamiccost.h
valhalla/sif/edgelabel.h

Separate Cost and TravelModes into new costconstants.h include. Add Cost to EdgeLabel (replace cost in seconds) - this allows EdgeLabel to track elapsed time along the path. Add TravelMode to EdgeLabel and cost methods

Changes to track elapsed time and mode along path

---

src/sif/autocost.cc
src/sif/dynamiccost.cc
src/sif/pedestriancost.cc
valhalla/sif/dynamiccost.h

we really needed the localedgeidx which is part of DirectedEdge.

Remove to_idx from TransitionCost

---

src/sif/edgelabel.cc
valhalla/sif/edgelabel.h

Rearrange fields to minimize size (increased from 56 bytes to 64 even though 4 new 4 byte fields were added).

Add transit information (tripId, prior stop Id, walking distance).

---

src/sif/bicyclecost.cc
src/sif/pedestriancost.cc

Also, remove the UnitSize override method in pedestrian so everything uses 1 for unit size.

Add bicycle defaults. TODO - allow overrides and document.

---

src/sif/dynamiccost.cc
src/sif/pedestriancost.cc
valhalla/sif/dynamiccost.h

In pedestrian costing allow transit connections when doing multimodal routes and disable when pedestrian only (don't want to cur through transit stations!).

Flag to disable use of transit connections

---

src/sif/autocost.cc
valhalla/sif/autocost.h

Great example in Pittsburgh:
Autos can not drive on East Busway.
Auto Costing:
http://localhost:8002/route?json={%22locations%22:[{%22lat%22:40.4141036,%22lon%22:-79.8766083},{%22lat%22:40.4145961,%22lon%22:-79.8777316}],%22costing%22:%20%22auto%22,%22directions_options%22:{%22units%22:%22miles%22}}&api_key=valhalla-T_YY31g
"maneuvers": [
{
"begin_shape_index": 0,
"length": 0.048,
"end_shape_index": 3,
"instruction": "Go north on South Braddock Avenue/Green Belt.",
"street_names": 
[
"South Braddock Avenue",
"Green Belt"
],
"type": 1,
"time": 0
},
{
"begin_shape_index": 3,
"length": 0.05,
"end_shape_index": 4,
"instruction": "Turn left onto Mc Kim Street.",
"street_names": 
[
"Mc Kim Street"
],
"type": 15,
"time": 22
},
Bus Costing: …

added bus costing.

---

valhalla/sif/hierarchylimits.h

Increase distance from destination where expansion on arterial level is allowed.

Use arterial further from destination

---

src/sif/dynamiccost.cc
src/sif/pedestriancost.cc
valhalla/sif/dynamiccost.h

(e.g. max walking distance for a segment of a multi-modal route). 
Add max mode distance for walking so we can limit the walking portions of transit routes.
TODO - should add mode specific maximum for bicycle when we get to that.

Add method to use max mode distances

---

src/sif/autocost.cc
src/sif/bicyclecost.cc
src/sif/dynamiccost.cc
src/sif/pedestriancost.cc
src/sif/transitcost.cc
valhalla/sif/dynamiccost.h

AllowedReverse and TransitionCostReverse.  These methods are used in bidirectional A* but could also be used in many to one paths which would be traversed in reverse.

Add costing methods for reverse path

---

src/sif/bicyclecost.cc

Validate config inputs. Decrease turn costs slightly and increase maneuver penalty. Add penalty when speed is over a threshold (threshold depends on useroads factor). Penalize driveways.

Bicycle Costing Adjustments

---

src/sif/autocost.cc
src/sif/bicyclecost.cc

avoids other computations and improves performance by 1-2% on long routes.

Optimize TransitionCost where stopimpact == 0

---

src/sif/autocost.cc
src/sif/bicyclecost.cc

Need to apply penalty when names are not consistent! Last PR separated this out incorrectly

Name consistency penalties were incorrectly applied. 

---

src/sif/autocost.cc
src/sif/bicyclecost.cc
src/sif/pedestriancost.cc

ferry_cost is applied to both the elapsed time and cost for path determination.
When use_ferry is < 0.5 it adds penalties to try to avoid using ferries. 
When use_ferry > 0.5 there are no penalites and the cost along a ferry is reduced (based on length of the ferry) to try to favor using a ferry vs. auto (which is usually faster).
Ferry logic is also applied to bicycle costing - when on a ferry the elapsed time and cost is based on the ferry speed (not the bicycling speed).

Add ferry_cost and use_ferry input option

---

src/sif/edgelabel.cc
valhalla/sif/edgelabel.h

Needed to add turn cost (separate from Cost) to allow use in the reverse path. When forming the path and computing elapsed time for the reverse path the elapsed time is formed by differences between the Cost elapsed times. However, this applies the turn cost at the wrong edge so this PR allows it to be added to the EdgeLabel separately. A future thor PR will alter the reverse path search and FormPath methods to use this.

Add turn cost

---

src/sif/bicyclecost.cc

They are allowed in the Allowed methods so this just makes it consistent.

Allow mountain bikes on kPath edges in the search filter

---

src/sif/dynamiccost.cc

Array sizes in sif/hierarchylimits.h have size 8. Maybe 8 should be replaced with something like sizeof(kDefaultMaxUpTransitions) / sizeof(kDefaultMaxUpTransitions[0]).
You can detect errors like this one by compiling with -fsanitize=address.

Fixed off by one in dynamic cost initialization.

---

src/sif/edgelabel.cc
valhalla/sif/edgelabel.h
valhalla/sif/hierarchylimits.h

Add to constructor for EdgeLabel (used in bidirectional A*).
Add a separate StopExpanding method to hierarchylimits - used in bidrectional A* where distance from destination is not a factor.

Change turn cost to transition cost

---

src/sif/dynamiccost.cc
src/sif/pedestriancost.cc
src/sif/transitcost.cc
valhalla/sif/dynamiccost.h

Costing was messed up for transit.  Updated cost and penalty. They were flipped. sigh.
Added defaults for walking between stops and at the beginning or end of a transit route.  
Tweaks here and there for desired defaults based on real world test cases.

make transit work correctly with new feeds.

---

src/sif/pedestriancost.cc
src/sif/transitcost.cc

This with thor updates fixes switching operators, taking buses when not needed, and take a more desired bus route.
<code><pre>
Avoid path example://
<    Depart: 8:05 AM from 23rd Street.
<    VERBAL_DEPART: Depart at 8:05 AM from 23rd Street.
< 4: Take the PATH toward Journal Square. (1 stop) | 0.4 mi
<    VERBAL_PRE: Take the PATH toward Journal Square.
<    VERBAL_POST: Travel 1 stop.
<    Arrive: 8:06 AM at 14th Street.
<    VERBAL_ARRIVE: Arrive at 8:06 AM at 14th Street.
< 5: Transfer at the 6 Av station. | 0.0 mi
<    VERBAL_PRE: Transfer at the 6 Av station.
<    VERBAL_POST: Continue for 20 feet.
<    Depart: 8:06 AM from 6 Av.
<    VERBAL_DEPART: Depart at 8:06 AM from 6 Av.
< 6: Take the L toward CANARSIE - ROCKAWAY PKWY. (9 stops) | 4.2 mi
<    VERBAL_PRE: Take the L toward …

lower mode weights

---

src/sif/edgelabel.cc
src/sif/pedestriancost.cc
valhalla/sif/edgelabel.h

High penalty to go directly from a transit connection to another at a transit node. This is to prevent entering a stop then exiting without taking transit.

Penalize transit connection transitions at a transit node

---

src/sif/pedestriancost.cc
src/sif/transitcost.cc

Influence the total transfer cost (time + penalty) by the transfer factor. 	Separate wait time from elapsed time and only apply penalty to transit elapsed time. Normalize factors to 1.0 as the lowest. Increase the penalty for stop to stop transfers. Set defaults if inputs are outside of range.
Reduce pedestrian mode weight within multimodal routes.

Transit costing and transfer changes

---

src/sif/autocost.cc

@dnesbitt61 do you see an issue with this new value.

0.6 was not enough for the reverse trip.  0.65 is enough.

---

src/sif/autocost.cc
src/sif/bicyclecost.cc
src/sif/pedestriancost.cc
src/sif/transitcost.cc
src/sif/truckcost.cc
valhalla/sif/dynamiccost.h

Did not need the opposing predecessor edge - just use the predecessor opposing local index. This
is safer anyway since this is handled when transitions between hierarchies are included.

Fix AllowedReverse use of turn restrictions.

---

scripts/dependencies.sh
scripts/install.sh
src/sif/pedestriancost.cc

Moved prevent going from one transit connection directly to another at a transit stop logic from sif to multimodal in thor.  We always want to avoid these in pedestrian mode.

moved logic to multimodal.cc

---

src/sif/autocost.cc
src/sif/bicyclecost.cc
src/sif/edgelabel.cc
src/sif/pedestriancost.cc
src/sif/truckcost.cc
valhalla/sif/edgelabel.h

Remove comments on not_thru edges. Add override method to set not_thru on predecessor.

Need both cost and time for transition costs to form proper connection for bidirectional A*.

---

src/sif/bicyclecost.cc
valhalla/sif/edgelabel.h

Fixes issue #88 
Reduce default maneuver penalty for bicycles.
Also, combine transit operator and block Id into a single int. Reduces structure size to 64 bytes.

Use higher of turn degree cost and crossing cost.

---

src/sif/autocost.cc
src/sif/bicyclecost.cc
src/sif/pedestriancost.cc
src/sif/transitcost.cc
src/sif/truckcost.cc
valhalla/sif/dynamiccost.h

0 means not allowed and values up to 1 indicate allowed, with higher values more favorable
for use as an edge for the location. This will allow ranking of edges and better selection of appropriate edges when numerous candidates exist.

Alter EdgeFilter to return a float value

---

src/sif/autocost.cc
src/sif/bicyclecost.cc
src/sif/edgelabel.cc
valhalla/sif/edgelabel.h

May want to also do this for others. This is needed since location heading can select an edge leading to a dead-end, rather than an outbound edge.

Allow U-turns at dead ends for auto routes.

---

src/sif/pedestriancost.cc

Initially thought this would improve performance but seems to actually degrade performance slightly. This will allow better map-matching of pedestrian paths.

Remove U-turn check. Pedestrians can make U-turns anywhere (in theory).

---

src/sif/dynamiccost.cc
src/sif/transitcost.cc
valhalla/sif/dynamiccost.h

before: using MTA
after: only use PATH
'{"locations":[{"lat":40.749706,"lon":-73.991562,"street":"Penn Plaza"},{"lat":40.730930,"lon":-73.991379,"street":"Wanamaker Place"}],"costing":"multimodal","directions_options":{"units":"miles"},"costing_options":{"transit":{"filters":{"operators":{"ids":["**o-dr5r-path**"],"action":"**only**"}}}},"date_time":{"type":1,"value":"2016-05-17T08:00"}}'

user can now Include/exclude transit lines.

---

src/sif/edgelabel.cc
valhalla/sif/edgelabel.h

This needs to be state that is passed in from the path algorithm. Once a thru edge is encountered on a path the not_thru_pruning flag is enabled. This fixes paths were both origin and destination are inside disconnected regions or places where both directions are marked as not_thru.

Add flag for not_thru_pruning. 

---

valhalla/sif/costfactory.h

Changed the error to match what use to be thrown inside of Loki but is now removed because of costing_option logic changes within Loki

CostFactory internal error update

---

src/sif/bicyclecost.cc
src/sif/pedestriancost.cc

Add penalty to roundabouts. Change bicycle penalty to be on driveways (not destination only roads). Add small penalty to destination only roads.
Fixes issue#148

Reduce the crossing cost for pedestrian routes when stop impact is low.

---

src/sif/dynamiccost.cc
src/sif/edgelabel.cc
valhalla/sif/dynamiccost.h
valhalla/sif/edgelabel.h

If the edge starts/ends (based on the search direction) it looks up the restrictions and walks the predecessor edge label to see if the predecessor path matches the restriction edges.

Add support for complex restrictions.

---

src/sif/autocost.cc
src/sif/dynamiccost.cc
src/sif/truckcost.cc
valhalla/sif/dynamiccost.h

For driving routes within bidirectional path algorithms this will prohibit entering a destination only edge. This is more effective than setting penalties to avoid shortcuts through destination only areas. 
This is with prior logic using a penalty - it takes a shortcut through a parking area:
This is with new logic - it now takes service roads without cutting though parking aisles:

Add support for DisableDestinationOnly

---

src/sif/autocost.cc
src/sif/bicyclecost.cc
src/sif/dynamiccost.cc
src/sif/pedestriancost.cc
src/sif/truckcost.cc

depends on valhalla/mjolnir#581
``` diff
< BEFORE
< Turn right onto Tysons Boulevard. | 0.2 mi
< Continue. | 0.2 mi
< Continue on Tysons Boulevard. | 0.3 mi
> AFTER
> Turn right onto Tysons Boulevard. | 0.7 mi
```

Ignore name inconsistency when entering a link to avoid double penalizing
